accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in$', views.sign_in, name='sign_in'),
    url(r'sign_up$', views.sign_up, name='sign_up'),
    url(r'sign_out$', views.sign_out, name='sign_out'),
    url(r'profile/(?P<pk>\d+)/$', views.show_profile, name='profile'),
    url(r'profile/edit/(?P<pk>\d+)/$', views.edit_profile, name='edit_profile'),
    url(r'profile/change_password/$', views.change_user_password, name='change_password'),
    url(r'profile/edit_image/$', views.edit_image, name='edit_image'),
]

user_profile_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

accounts/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="profile", null=False)
    date_of_birth = models.DateField(null=True, blank=True)
    biography = models.TextField(default='Awaiting users story', blank=True)
    avatar = models.FilePathField(blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    def get_absolute_url(self):
        return reverse('accounts:profile', kwargs={
            'pk': self.user.pk
        })

    def generate_file_path(self):
        user_path = 'images\\user_avatars' + '\\{}-{}.jpeg'.format(
            self.user.first_name, self.user.last_name
        )
        return user_path

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.core import validators
from django.forms import (
        CharField, DateInput, EmailField, Form, FileInput,
        HiddenInput, ModelForm, TextInput, ValidationError,
        PasswordInput, FileField
    )

from collections import namedtuple
from bs4 import BeautifulSoup

from . import models
from accounts.validators import password_checker, check_empty


TempUserObject = namedtuple('TempUserObject', ['username', 'first_name', 'last_name'])


class UserAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise ValidationError(
                message="Account inactive, cant log you in",
                code='Inactive',
            )


class SignUpForm(Form):
    username = CharField(required=True)
    first_name = CharField(required=True)
    last_name = CharField(required=True)
    email = EmailField(
        required=True,
        validators=[validators.EmailValidator()]
    )
    confirm_email = EmailField(
        required=True,
        label="Confirm email"
    )
    tar_pit_trap = CharField(
        required=False,
        widget=HiddenInput,
        label="leave this blank",
        validators=[check_empty]
    )
    password = CharField(
        required=True,
        widget=PasswordInput,
        label='Create password',
    )

    confirm_password = CharField(
        required=True,
        widget=PasswordInput,
        label='Confirm password'
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError(
                "The username {} is in use already".format(username),
                code='TakenUsername'
            )
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError(
                message="The email {} is in use already".format(email),
                code="TakenEmail",
            )
        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        temp_user_obj = TempUserObject(
            username=self.cleaned_data['username'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name']
        )
        p_check = password_checker(password, userObj=temp_user_obj)
        if p_check is not None:
            error = '\n'.join(p_check)
            raise ValidationError(
                message=error,
                code='BadPassword'
            )
        return password

    def clean(self):
        data = super().clean()
        email1 = data.get('email')
        email2 = data.get('confirm_email')
        if email1 != email2:
            raise ValidationError(
                message='Emails do not match!',
                code="DoesNotMatchEmail",
            )
        p1 = data.get('password')
        p2 = data.get('confirm_password')
        if p1 != p2:
            raise ValidationError(
                message='Passwords do not match!',
                code='DoesNotMatchPassword'
            )


class EditProfileForm(ModelForm):
    avatar = FileField(
        label="Upload Your Profile Picture Here",
        widget=FileInput,
        required=False
    )

    class Meta:
        model = models.UserProfile
        fields = (
            'date_of_birth',
            'biography',
        )
        widgets = {
            'date_of_birth': DateInput(attrs={
                'class': 'datepicker',
            }),
            'biography': TextInput(attrs={
                'class': 'textarea',
            }),
        }
        labels = {
            'date_of_birth': 'Date of birth'
        }

    def clean_biography(self):
        bio = BeautifulSoup(
            self.cleaned_data['biography'],
            'html5lib'
        ).get_text(strip=True)
        if len(bio) < 10:
            raise ValidationError(
                "Your Biography should be more than 10 characters"
            )
        return bio


class ChangePasswordForm(Form):
    current_password = CharField(
        required=True,
        widget=PasswordInput,
    )
    new_password = CharField(
        required=True,
        widget=PasswordInput,
    )
    confirm_new_password = CharField(
        required=True,
        widget=PasswordInput,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_old_password(self):
        current_password = self.cleaned_data.get('current_password')
        if not check_password(current_password, self.user.password):
            raise ValidationError(
                "You current password is incorrect"
            )
        return current_password

    def clean_new_password(self):
        new_password = self.cleaned_data['new_password']
        val_fails = password_checker(new_password, userObj=self.user, oldPword=self.user.password)
        if val_fails:
            error = '\n'.join(val_fails)
            raise ValidationError(
                message=error,
                code='BadPassword'
            )
        return new_password

    def clean(self):
        data = super().clean()
        new_password1 = data.get('new_password', None).strip()
        new_password2 = data.get('confirm_new_password', None).strip()
        if new_password1 != new_password2:
            raise ValidationError(
                message='Passwords do not match!',
                code='DoesNotMatchPassword'
            )

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect

import os

from . import models
from . import forms


def handle_file_upload(file, file_destination):
    file_destination = os.path.join("assets", file_destination)
    with open(file_destination, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)


def sign_up(request):
    if request.method == 'POST':
        form = forms.SignUpForm(data=request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            new_user = User(
                username=form_data['username'],
                first_name=form_data['first_name'],
                last_name=form_data['last_name'],
                email=form_data['email'],
            )
            new_user.set_password(form_data['password'])
            new_user.save()
            new_profile = models.UserProfile(user=new_user)
            new_profile.save()
            user = authenticate(
                username=form_data['username'],
                password=form_data['password']
            )
            login(request, user)
            messages.add_message(
                request,
                messages.SUCCESS,
                message="You are signed up, logged in, and can "
                        "complete your profile",
            )
            return redirect('accounts:edit_profile', pk=user.pk)
    else:
        form = forms.SignUpForm()
    return render(request, 'accounts\sign_up.html', {'form': form})


def sign_in(request):
    form = forms.UserAuthenticationForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(user.profile.get_absolute_url())
            else:
                messages.add_message(request,
                                     level=messages.ERROR,
                                     message="Account Inactive")
        else:
            messages.add_message(
                request,
                level=messages.ERROR,
                message="Invalid details, or user does not exist"
            )
    return render(request, 'accounts\sign_in.html', {'form': form})


@login_required
def sign_out(request):
    logout(request)
    messages.add_message(request, level=messages.SUCCESS, message="Logged out successfully")
    return redirect('home')


@login_required
def show_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    privileged = False
    if user == request.user:
        privileged = True
    profile = get_object_or_404(models.UserProfile, user=user)
    context = {
        'profile': profile,
        'privileged': privileged,
    }
    template = 'accounts\profile.html'
    return render(request, template, context)


@login_required
def edit_profile(request, pk):
    profile_to_edit = get_object_or_404(
        models.UserProfile,
        user=request.user
    )
    form = forms.EditProfileForm(instance=profile_to_edit)
    if request.method == 'POST':
        form = forms.EditProfileForm(
            request.POST or None,
            request.FILES,
            instance=profile_to_edit,
        )
        if form.is_valid():
            profile_to_edit = form.save(commit=False)
            profile_to_edit.avatar = profile_to_edit.generate_file_path()
            if request.FILES:
                handle_file_upload(
                    request.FILES['avatar'],
                    profile_to_edit.avatar
                )
            profile_to_edit.save()
            messages.success(request, message="Your profile is updated")
            return HttpResponseRedirect(profile_to_edit.get_absolute_url())
    return render(request, 'accounts\edit_profile.html', {'form': form})


@login_required
def edit_image():
    pass


@login_required
def change_user_password(request):
    form = forms.ChangePasswordForm()
    if request.method == 'POST':
        form = forms.ChangePasswordForm(request.POST, user=request.user)
        if form.is_valid():
            u = form.user
            u.set_password(request.POST['new_password'])
            u.save()
            update_session_auth_hash(request, u)
            messages.success(
                request,
                message="Your password has been changed"
            )
            HttpResponseRedirect(u.profile.get_absolute_url())
    return render(request, 'accounts\change_password.html', {'form': form})

templates/accounts/change_password.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} | Change Password{% endblock title %}

{% block bodyContent %}
    <div class="grid-75">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Change Password">
        </form>
    </div>
{% endblock bodyContent %}

templates/accounts/edit_profile.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} | Edit Profile{% endblock title %}

{% block bodyContent %}
    <div class="grid-75">
        <h1>Hello {{ user.first_name }}</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save Changes" class="button-primary">
        </form>
    </div>
{% endblock bodyContent %}

templates/accounts/profile.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    {{ block.super }} | {{ profile.user.first_name }} {{ profile.user.last_name }}
{% endblock %}


{% block bodyContent %}
    <div class="grid-75">
        <h1>{{ profile.user.first_name}}'s Profile</h1>
        {% if profile.avatar %}
            <div class="circle--primary--avatar">
                <img src="{% static "" %}{{ profile.avatar }}"
                     alt="{{ profile.user.first_name }} {{ profile.user.last_name }} Picture">
            </div>
        {% endif %}
            <table class="circle--table">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
                <tr>
                    <td>{{ profile.user.first_name }}</td>
                    <td>{{ profile.user.last_name }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                </tr>
                <tr>
                    <td>{{ profile.user.email }}</td>
                </tr>
                <tr>
                    <th>Birthday</th>
                </tr>
                <tr>
                    <td>{{ profile.date_of_birth|date:"j F"}}</td>
                </tr>
                <tr>
                    <th>Biography</th>
                </tr>
                <tr>
                    <td>{{ profile.biography }}</td>
                </tr>
            </table>
        {% if privileged %}
            <a href="{% url 'accounts:edit_profile' pk=user.pk %}">Edit</a>
            <a href="{% url 'accounts:change_password' %}">Change Password</a>
        {% endif %}
    </div>
{% endblock bodyContent %}

templates/accounts/sign_in.html
{% extends 'layout.html' %}

{% block title %}
    {{ block.super }} | Sign In
{% endblock title %}

{% block bodyContent %}
    <div class="grid-75">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login">
        </form>
    </div>
{% endblock bodyContent %}

templates/accounts/sign_out.html
{% extends 'layout.html' %}

templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}
    {{ block.super }} | Sign Up
{% endblock title %}

{% block bodyContent %}
    <div class="grid-75">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign Up">
        </form>
    </div>
{% endblock bodyContent %}