accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in$', views.sign_in, name='sign_in'),
    url(r'sign_up$', views.sign_up, name='sign_up'),
    url(r'sign_out$', views.sign_out, name='sign_out'),
    url(r'profile/(?P<pk>\d+)/$', views.show_profile, name='profile'),
    url(r'profile/edit/(?P<pk>\d+)/$', views.edit_profile, name='edit_profile'),
    url(r'profile/change_password/$', views.change_user_password, name='change_password'),
    url(r'profile/edit_image/$', views.edit_image, name='edit_image'),
]

user_profile_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    {% if user.is_authenticated %}
        {{ block.super }} | Profiles
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock title %}

{% block bodyContent %}
    <div class="grid-25">
    </div>
    <div class="grid-75">
        <h1>Welcome!</h1>
        {% if user.is_authenticated %}
            <h2>Here are our currently active user's</h2>
            <hr>
                <ul>
                    {% for user in users %}
                        <li>
                            <a href="{% url 'accounts:profile' pk=user.user.pk %}">
                                {{ user.user.first_name }} {{ user.user.last_name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
        {% else %}
            <h2>Please log in to see our users</h2>
        {% endif %}
    </div>
{% endblock bodyContent%}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">
    {% block css %}
    {% endblock css %}

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript"
            src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>
    {% block javascript %}
    {% endblock javascript %}

</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% block bodyContent %}
{% endblock bodyContent%}
</body>
</html>